services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: taskflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  taskflow-api:
    build:
      context: .
      dockerfile: TaskFlow/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=taskflow_db;Username=postgres;Password=12345678

volumes:
  postgres_data: